apiVersion: v1
data:
  Corefile: |-
    .:53 {
        errors
        health {
            lameduck 5s
          }
        ready

        hosts {
          10.254.35.46 gitlab.dev01.gov.bh
          10.254.36.127 gitlab.dev01.gov.bh
          fallthrough
        }

        rewrite name exact cyber.uat01.gov.bh a64bedfef12b2472b8fafdb05cee5aff-d299e254776a1189.elb.eu-west-1.amazonaws.com
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  labels:
    eks.amazonaws.com/component: coredns
    k8s-app: kube-dns
  name: coredns
  namespace: kube-system
